apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-auto-scale-test
  labels:
    app: k8s-auto-scale-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-auto-scale-test
  template:
    metadata:
      labels:
        app: k8s-auto-scale-test
    spec:
      containers:
      - name: server
        image: k8s-auto-scale-test
        imagePullPolicy: Always
        command: ["/app/server"]
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 1000m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
